spring:
  profiles:
    active: tina
  mvc:
    throw-exception-if-no-handler-found: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  resources:
    add-mappings: false

server:
  error:
    whitelabel:
      enabled: false
