es:
  authentication: false
  user: gateway
  passwd: gateway
  addresses: 127.0.0.1:9500
zabbix:
  host: 127.0.0.1
  serverport: 10051
  apiport: 8888
  user: Admin
  passwd: zabbix
  defaultHostgroup: bigdata

server:
  port: 8082
  #context-path: /
  debug: true


